//! Autogenerated weights for pallet_shadow
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `shadowchain`, CPU: `Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz`
//! WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/shadowchain
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet_shadow
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/shadow/src/weights.rs

#![cfg_attr(not(feature = "std"), no_std)]

use polkadot_sdk::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_shadow.
pub trait WeightInfo {
	fn submit_shadow_item() -> Weight;
	fn delete_shadow_item() -> Weight;
	fn grant_consent() -> Weight;
	fn revoke_consent() -> Weight;
}

/// Weights for pallet_shadow using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Shadow::ConsentRecords` (r:1 w:0)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Shadow::ShadowItems` (r:1 w:1)
	/// Proof: `Shadow::ShadowItems` (`max_values`: None, `max_size`: Some(8841), added: 11316, mode: `MaxEncodedLen`)
	fn submit_shadow_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `12306`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 12306)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ShadowItems` (r:1 w:1)
	/// Proof: `Shadow::ShadowItems` (`max_values`: None, `max_size`: Some(8841), added: 11316, mode: `MaxEncodedLen`)
	fn delete_shadow_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `12306`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 12306)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ConsentRecords` (r:0 w:1)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn grant_consent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ConsentRecords` (r:0 w:1)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn revoke_consent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `Shadow::ConsentRecords` (r:1 w:0)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Shadow::ShadowItems` (r:1 w:1)
	/// Proof: `Shadow::ShadowItems` (`max_values`: None, `max_size`: Some(8841), added: 11316, mode: `MaxEncodedLen`)
	fn submit_shadow_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `12306`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 12306)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ShadowItems` (r:1 w:1)
	/// Proof: `Shadow::ShadowItems` (`max_values`: None, `max_size`: Some(8841), added: 11316, mode: `MaxEncodedLen`)
	fn delete_shadow_item() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `12306`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 12306)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ConsentRecords` (r:0 w:1)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn grant_consent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Shadow::ConsentRecords` (r:0 w:1)
	/// Proof: `Shadow::ConsentRecords` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn revoke_consent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}